### ISSUE TITLE
Incompatible with Python 3.3

### ISSUE THREAD

**Issue by mat8913** [jpakkane/meson#101]
readme.txt has Python version 3.3 or newer listed as a dependency but the minimum version of Python that actually works with meson is 3.4.

When I attempted to run meson with Python 3.3, I received the following error:

    Traceback (most recent call last):
      File "/usr/local/bin/meson", line 184, in <module>
        app.generate()
      File "/usr/local/bin/meson", line 130, in generate
        intr.run()
      File "/usr/local/share/meson/interpreter.py", line 830, in run
        self.evaluate_codeblock(self.ast)
      File "/usr/local/share/meson/interpreter.py", line 852, in evaluate_codeblock
        raise e
      File "/usr/local/share/meson/interpreter.py", line 846, in evaluate_codeblock
        self.evaluate_statement(cur)
      File "/usr/local/share/meson/interpreter.py", line 897, in evaluate_statement
        return self.assignment(cur)
      File "/usr/local/share/meson/interpreter.py", line 1565, in assignment
        self.set_variable(var_name, value)
      File "/usr/local/share/meson/interpreter.py", line 887, in set_variable
        if re.fullmatch('[_a-zA-Z][_0-9a-zA-Z]*', varname) is None:
    AttributeError: 'module' object has no attribute 'fullmatch'

re.fullmatch is a feature introduced in Python 3.4.
